[package]
name = "raytracer"
version = "0.1.0"
authors = ["SokichiFujita <sokichi.fujita@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
approx = "0.4.0"
nalgebra = "0.23.2"
ulid = "0.4.1"
